name: lyra-builder

description: Build lyra binary on different platforms

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        bazelisk build -c opt lyra/cli_example:decoder_main
