name: lyra-builder

description: Build lyra binary on different platforms

inputs:
  platform:
    description: Platform to build
    required: true
  architecture:
    description: Architecture to build
    required: true
  build-options:
    description: Options in bazel build command
    required: false
    default: ""

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        bazel build -c opt lyra/cli_example:encoder_main
    - shell: bash
      run: |
        mkdir action-product
        cp -r lyra/model_coeffs action-product/
        cp bazel-bin/lyra/cli_example/encoder_main action-product/lyra-encoder
        cp bazel-bin/lyra/cli_example/decoder_main action-product/lyra-decoder
    - uses: actions/upload-artifact@v2
      with:
        name: lyra-${{ inputs.platform }}-${{ inputs.architecture }}
        path: action-product
