name: setup-lyra-deps

description: Setup python for lyra build

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;21.4.7075529"
        python3 -m pip install --upgrade pip
        pip install numpy
