name: setup-lyra-deps

description: Setup python for lyra build

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install numpy
