name: build

on:
  workflow_dispatch:

jobs:
  linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Setup Lyra dependencies
        uses: ./.github/actions/setup-lyra-deps
      - name: Build and upload
        uses: ./.github/actions/lyra-builder